/* 
	the format of the tree definition file is simple,
		you can find specification in the Tigra Menu documentation at:
	
	
*/
var TREE_ITEMS = [
	['Home', 'main.htm', 
		['Scheme Programme Management', null,
			['Scheme',null,
				['Manage Scheme','SchemeProgramManagement/SPM_SearchScheme_Division.html'],
				['Scheme Sanction','SchemeProgramManagement/SchemeSanction/SPM_SS_SchemeReceived.html'],
			],
			['Schedule of Rates','SchemeProgramManagement/ScheduleOfRates/SPM_ScheduleOfRates.html'],
			/*
			['Scheme Initialization',null,
				['',''],	
			],			
			['Scheme Preparation',null,				
				['Initial Investigation for Scheme', 'SchemeProgramManagement/SchemePreparation/SPM_SchemePreparation_InitialInvestigation_DE.html'],
				
				['Forecasting',null,
					['',''],
				],
				['Estimation',null,
					['',''],
				],
				['Income', null,
					['Assumptions for Annual Income', 'SchemeProgramManagement/SchemePreparation/Income/SPM_SchemePreparation_Income_Assumptions_DE_22.html'],
				],
				["Expenditure",null,
					['Annual Expenditure of Chemicals', 'SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_Chemical_DE_17.html'],
					['Annual Expenditure of Electricity', 'SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_Electricity_DE_18.html'],
					['Annual Expenditure of Maintainance Staff', 'SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_MaintenenceStaff_DE_20.html'],
					['Annual Expenditure of Repairing Charges', 'SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_Repairing_DE_19.html'],
				],
				['Financial Statements',null,
					['Civil Works','SchemeProgramManagement/SchemePreparation/FinancialStatement/SPM_SchemePreparation_FinancialStatement_FormJ_Civil_DE_11.html'],
					['E & M','SchemeProgramManagement/SchemePreparation/FinancialStatement/SPM_SchemePreparation_FinancialStatement_FormJ_EM_DE_12.html'],
				],	
				['Add New Scheme','SchemeProgramManagement/SchemePreparation/SPM_SchemePreparation_AddNewScheme_DE.html'],
			],
			
			['Scheme Sanction',null,
				['',''],	
			] ,	
			['Scheme Execution',null,
				['',''],	
			],		
			['Scheme Monitoring',null,
				['',''],	
			] ,	
			['Scheme Maintenance',null,
				['',''],	
			] ,	

			['Statements',null,
				['Show Statements','SchemeProgramManagement/search_Scheme_Division_STMT.html']
				['Statement Showing Assumptions','SchemeProgramManagement/SchemePreparation/Income/SPM_SchemePreparation_Income_Assumptions_STMT_22.html'],
				['Statement of Annual Income','SchemeProgramManagement/SchemePreparation/Income/SPM_SchemePreparation_Income_AnnualIncome_STMT_23.html'],
				['Annual Expenditure on Chemicals','SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_Chemical_STMT_17.html'],
				['Annual Expenditure on Electricity','SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_Electricity_STMT_18.html'],				
				['Annual Expenditure on Repairing','SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_Repairing_STMT_19.html'],
				['Annual Expenditure on Maintenance Staff','SchemeProgramManagement/SchemePreparation/Expenditure/SPM_SchemePreparation_Expenditure_MaintenenceStaff_STMT_20.html'],
				['Statement showing Per Capita Cost','SchemeProgramManagement/SchemePreparation/SPM_SchemePreparation_PerCapitaCost_STMT_15.html'],
				['Statement showing Economics','SchemeProgramManagement/SchemePreparation/SPM_SchemePreparation_Economics_STMT_21.html'],
				['Form - J (Comprehensive)','SchemeProgramManagement/SchemePreparation/FinancialStatement/SPM_SchemePreparation_FinancialStatement_FormJ_Comp_STMT_10.html'],
				['Form - J (Civil Works)','SchemeProgramManagement/SchemePreparation/FinancialStatement/SPM_SchemePreparation_FinancialStatement_FormJ_Civil_STMT_11.html'],
				['Form - J (E & M Works)','SchemeProgramManagement/SchemePreparation/FinancialStatement/SPM_SchemePreparation_FinancialStatement_FormJ_EM_STMT_12.html'],
				['General Abstract Of Cost (Civil Works)','SchemeProgramManagement/SchemePreparation/FinancialStatement/SPM_SchemePreparation_FinancialStatement_Abstract_Civil_STMT_13.html'],
				['General Abstract Of Cost (E & M Works)','SchemeProgramManagement/SchemePreparation/FinancialStatement/SPM_SchemePreparation_FinancialStatement_Abstract_EM_STMT_14.html'],
				
			],
			['Others',null,
				['Measurement Book','SchemeProgramManagement/Others/SPM_Others_MeasurementBook.html'],
				['Plan & Estimation Preparation','SchemeProgramManagement/Others/SPM_Others_PlanEstimatePreparation.html'],
				['Yearly O&M Estimate Preparation','SchemeProgramManagement/Others/SPM_Others_YearlyEstimatePreparation.html'],
				['Habitation Wise Target','SchemeProgramManagement/Others/SPM_Others_HabitationWiseTarget.html'],
				['Works Master','SchemeProgramManagement/Others/SPM_Others_WorksMaster.html'],
				['Source Master','SchemeProgramManagement/Others/SPM_Others_SourceMaster.html'],
				['Agency Master','SchemeProgramManagement/Others/SPM_Others_AgencyMaster.html'],
			],			
			*/
		],	
		['Water Quality Management',null,
			['Sample Collection Details','WaterQualityManagement/WQM_SampleCollectionDetails_DE.html'],
			['Manage test parameters','WaterQualityManagement/WQM_ManageTestParameter_DE.html'],
			['Lab Master','Master/Master_LabMaster_DE.html'],
			['Capturing test results','WaterQualityManagement/WQM_ListTestResults_DE.html'],
			['Sample Wise Test Reports','WaterQualityManagement/WQM_SearchSampleToViewReport.html'],
			['Test Report of all samples','WaterQualityManagement/WQM_RPTTestDetailsofAllSamples.html'],
			
		],
		['Resource Management',null,
			['Habitation Baseline Information','ResourceManagement/RM_VillageBaseLineInfo_DE.html'],
			['Water Source Information','ResourceManagement/RM_WaterSourceInfo_DE.html'],
			['Public Institution Coverage','ResourceManagement/RM_PublicInstitutionInformation_DE.html'],
			['District wise School Coverage','ResourceManagement/Master_SchoolInfoUnderDistrict_DE.html'],
			//['Source Commision Details',''],
		],
		['Role Management', null,
			['Office Master (SU)','RoleManagement/RM_OfficeMaster_ListOffices.html'],
			//['Create Office Admin (SU)','RoleManagement/RM_CreateOfficeAdmin_ListOfficeAdmin.html'],
			['Assign Office Admin (SU)','RoleManagement/RM_AssignOfficeAdmin_ListOfficeAdmin.html'],
			['Define Role (OA)','RoleManagement/RM_DefineRole_ListRoles.html'],
			['Create User (OA)','RoleManagement/RM_CreateUser_ListUsers.html'],
			['Modify User Roles (OA)','RoleManagement/RM_ModifyUserRoles_ListUsers.html'],
			['Change Password','RoleManagement/RM_CreateUser_ChangePassword.html'],
		],
		['Master',null,
			['State Master','Master/Master_State_DE.html'],
			['District Master','Master/Master_District_DE.html'],
			['Block Master','Master/Master_Block_DE.html'],
			['Tehsil Master','Master/Master_Tehsil_DE.html'],
			['Panchayat Master','Master/Master_Panchayat_DE.html'],
			['Village Master','Master/Master_village_DE.html'],
			['Habitation Master','Master/Master_Habitation_DE.html'],
			['Parliament Master','Master/Master_Parliament_DE.html'],
			['Assembly Master','Master/Master_Assembly_DE.html'],
			['Supply-System Master','Master/Master_WaterSystem_DE.html'],
			['Scheme Programme Management',null,
				['Labour Master','Master/SPM/Master_LabourMaster_DE.html'],
				['Works Master','Master/SPM/Master_WorksMaster_DE.html'],			 	
				['Cartage Master','Master/SPM/Master_CartageMaster_DE.html'],
				['Pipe Master','Master/SPM/Master_PipeMaster_DE.html'],
				['Valve Master','Master/SPM/Master_ValveMaster_DE.html'],				
			],
			['Personnel & Payroll Masters',null,
				['Employee Master','Master/PPIS/xxxx'],
				['Designation Master','Master/PPIS/xxxx'],			 	
				['Leave  Master','Master/PPIS/Master_CartageMaster_DE.html'],
				['Allowance Master','Master/PPIS/xxxx'],				
			],

		],
		['Personnel Management', null,
			['Service Book','PPIS/servicebook_entries.html'],
			['Personnel 1',''],
			['Personnel 2',''],
		],
	]
];

